services:
  api:
    build:
      context: weti-api
      dockerfile: Dockerfile  # Path to the Dockerfile
    container_name: weti_api  # Optional: Name the container for easier management
    ports:
      - "${WETI_API_PORT:-3000}:${WETI_API_PORT:-3000}"
    restart: unless-stopped  # Restart policy for the container
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${WETI_DB_PASSWORD}

networks:
  default:
    driver: bridge
