services:
  queue:
    build:
      context: weti-queue
      dockerfile: Dockerfile
    container_name: weti-queue
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 1.0.0.1
    env_file:
      - .env
    depends_on:
      - api
    volumes:
      - ./config.toml:/usr/src/app/config.toml   
    environment:
      WETI_DB_URL: postgres://postgres:${WETI_DB_PASSWORD}@db:5432/postgres

  api:
    build:
      context: weti_api
      dockerfile: Dockerfile  
    container_name: weti_api 
    ports:
      - "${WETI_API_PORT:-3000}:${WETI_API_PORT:-3000}"
    restart: unless-stopped  # Restart policy for the container
    depends_on:
      - db
    env_file:
      - .env
    environment:
      WETI_DB_URL: postgres://postgres:${WETI_DB_PASSWORD}@db:5432/postgres

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${WETI_DB_PASSWORD}

networks:
  default:
    driver: bridge