import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useAccount, useBalance, useWalletClient } from 'wagmi';

import { AlchemyRPC } from '../makeRPC';
import { Provider, useJob } from '../createJob';
import generatePostgresTimestamp from '../makeDate';

const Home: NextPage = () => {
  const account = useAccount()
  const tokenBalanceJob = useJob({
    chainId: 8453,
    expiration: `${generatePostgresTimestamp({ months: 3 })}`,
    frequency: 10,
    provider: Provider.alchemy,
    rpc: AlchemyRPC.getTokenBalanceForAddress((account.address as string) , ["0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"])
  })

  console.log(tokenBalanceJob)

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton label="Sign in" accountStatus={{
          smallScreen: 'avatar',
          largeScreen: 'full',
        }} />
      </main>
    </div>
  );
};

export default Home;
